### ISSUE TITLE
Path with ending Slash is not recognized

### ISSUE THREAD

**Issue by solakram** [Lacr1ma/routes#15]
Routes.yml

Works:
```
seamrest_user_register:
  path: rest/api/User/register
  controller: Seam\SeamRest\Controller\UserController::register
  defaults:
    plugin: Rest
```
    
Doesnt Work:
```
seamrest_user_register:
  path: rest/api/User/register/
  controller: Seam\SeamRest\Controller\UserController::register
  defaults:
    plugin: Rest
```

if the path has a slash at the end, the route cant be found and a 404 will be thrown

Tag 2.0.0
TYPO3 10.4.14

**Comment by solakram** [comment]
If the ending backslash works or not is handled by the routEnhancer configuration:

```
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: '/'
```

so i guess this is not a bug or a needed feature for this extension
