### ISSUE TITLE
Response 404 - Page not found when calling route

### ISSUE THREAD

**Issue by devmes** [Lacr1ma/routes#9]
TYPO3 Version: 10.4

If you specify a "base", e.g. "/de/" in the Site Config for the default language,
then the routes do not work anymore and you get "Page not found".
This happens because the middleware "typo3/cms-frontend/base-redirect-resolver" needs a language, otherwise a PageNotFound Action is called.

Example SiteConfig:
```yaml
base: www.sample.com
languages:
  -
    title: German
    base: /de/
    languageId: '0'.
  -
    title: Italian
    base: /it/
    language: '1'.
```

I have tested it with the following routes, without success
- api/demo/test
- en/api/demo/test
- it/api/demo/test

The workaround for me is to insert a middleware between "typo3/cms-frontend/base-redirect-resolver" and "lms/routes/extbase-route-resolver" which, if a route is found, sets the default language.
